//@flow
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const GET_FAVORITES = 'GET_FAVORITES';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const FavoriteActionTypes = {
	ADD_FAVORITE,
	GET_FAVORITES,
	CLEAR_FAVORITES,
	TOGGLE_FAVORITES,
	REMOVE_FAVORITE,
};
