//@flow
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const GET_FAVORITE_IDS = 'GET_FAVORITES';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const MAP_FAVORITE_POST_DATA  = 'MAP_FAVORITE_POST_DATA';

export const FavoriteActionTypes = {
	ADD_FAVORITE,
	GET_FAVORITE_IDS,
	CLEAR_FAVORITES,
	TOGGLE_FAVORITES,
	REMOVE_FAVORITE,
    MAP_FAVORITE_POST_DATA,
};
